name = "ACE3 Arsenal Extended - ACR_A3"
prefix = "aceax_compat_acr_a3"
author = "Piraj"
mainprefix = "x"

[hemtt.release]
archive = false # Default: true

[hemtt.launch.default]
presets = [
    "main",
]

[version]
major = 1
minor = 0
patch = 0